#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: AI Radar local and GitHub setup.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

banner "AI Radar setup"

stage "Local Python"
say "Create an isolated Python 3.12 environment and install the small default stack."
PYTHON_BIN=""
for candidate in python3.12 python3; do
  if command -v "$candidate" >/dev/null 2>&1 && "$candidate" -c 'import sys; raise SystemExit(sys.version_info < (3, 12))'; then
    PYTHON_BIN="$candidate"
    break
  fi
done
if [[ -z "$PYTHON_BIN" ]]; then
  warn "Python 3.12 or newer is required."
  exit 1
fi
"$PYTHON_BIN" -m venv .venv
.venv/bin/python -m pip install -e '.[dev]'
write_env RADAR_DB "data/local.db"
write_env RADAR_PDF_EXTRACTOR "pypdf"
say "The local database is ignored by Git and separate from the historical archive."

stage "Kimi API"
say "Choose the same platform region where your API credits were created."
ask KIMI_REGION "Platform [international/china] (international):"
KIMI_REGION="${KIMI_REGION:-international}"
case "$KIMI_REGION" in
  international)
    KIMI_BASE_URL="https://api.moonshot.ai/v1"
    KIMI_KEYS_URL="https://platform.kimi.ai/console/api-keys"
    ;;
  china)
    KIMI_BASE_URL="https://api.moonshot.cn/v1"
    KIMI_KEYS_URL="https://platform.kimi.com/console/api-keys"
    ;;
  *)
    warn "Choose either international or china."
    exit 1
    ;;
esac
open_url "$KIMI_KEYS_URL"
step "Create or copy an API key from the Kimi console."
ask_secret KIMI_API_KEY "Paste the Kimi API key:"
if [[ -z "$KIMI_API_KEY" ]]; then
  warn "A Kimi API key is required to run the research pipeline."
  exit 1
fi
write_env RADAR_LLM_PROVIDER "kimi"
write_env KIMI_API_KEY "$KIMI_API_KEY"
write_env RADAR_KIMI_BASE_URL "$KIMI_BASE_URL"

stage "Your fork"
DETECTED_REPOSITORY=""
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  DETECTED_REPOSITORY=$(gh repo view --json nameWithOwner -q .nameWithOwner 2>/dev/null || true)
fi
if [[ -n "$(_existing RADAR_REPOSITORY || true)" ]]; then
  ask RADAR_REPOSITORY "GitHub repository (owner/name):"
elif [[ -n "$DETECTED_REPOSITORY" ]]; then
  say "Detected GitHub repository: $DETECTED_REPOSITORY"
  if confirm "Use this repository for report requests and Pages?"; then
    RADAR_REPOSITORY="$DETECTED_REPOSITORY"
  else
    ask RADAR_REPOSITORY "GitHub repository (owner/name):"
  fi
else
  ask RADAR_REPOSITORY "GitHub repository (owner/name):"
fi
if [[ ! "$RADAR_REPOSITORY" =~ ^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$ ]]; then
  warn "Repository must use the owner/name format."
  exit 1
fi
RADAR_OWNER="${RADAR_REPOSITORY%%/*}"
RADAR_NAME="${RADAR_REPOSITORY#*/}"
if [[ "$RADAR_NAME" == "$RADAR_OWNER.github.io" ]]; then
  RADAR_BASE_PATH=""
else
  RADAR_BASE_PATH="/$RADAR_NAME"
fi
RADAR_SITE_URL="https://$RADAR_OWNER.github.io$RADAR_BASE_PATH"
write_env RADAR_REPOSITORY "$RADAR_REPOSITORY"
write_env RADAR_SITE_BASE_PATH "$RADAR_BASE_PATH"
write_env RADAR_SITE_URL "$RADAR_SITE_URL"

if confirm "Configure GitHub Actions for this repository now?"; then
  export GH_REPO="$RADAR_REPOSITORY"
  set_secret KIMI_API_KEY "$KIMI_API_KEY"
  set_var RADAR_DB "data/radar-state.db"
  set_var RADAR_LLM_PROVIDER "kimi"
  set_var RADAR_KIMI_BASE_URL "$KIMI_BASE_URL"
  set_var RADAR_PDF_EXTRACTOR "pypdf"
  open_url "https://github.com/$RADAR_REPOSITORY/settings/pages"
  step "Under Build and deployment, select GitHub Actions as the source."
  pause "Press Enter after saving the Pages setting."
else
  SKIPPED+=("GitHub Actions configuration")
fi

stage "Verify"
say "Initialize local state, validate configuration, and run the offline test suite."
.venv/bin/ai-radar-doctor --init
.venv/bin/python -m pytest -q

finish
say "Activate the environment: source .venv/bin/activate"
say "Run a paid rehearsal when ready: ai-radar --dry-run"
say "Run one corpus report in Actions: gh workflow run research-corpus.yml -f mode=canary"
warn "The pipeline rehearsal calls the configured LLM and can spend API credits."
